# Generated by Django 2.2.9 on 2020-02-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200213_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bad_review',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='good_review',
            field=models.IntegerField(default=0),
        ),
    ]
