# Generated by Django 2.2.9 on 2020-02-10 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255, verbose_name='카테고리명')),
                ('univ_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='account.Univ', verbose_name='대학')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.URLField()),
                ('title', models.CharField(max_length=255, verbose_name='가게명')),
                ('star', models.CharField(max_length=255, verbose_name='별점')),
                ('min_price', models.PositiveIntegerField(verbose_name='최소주문금액')),
                ('del_time', models.PositiveIntegerField(verbose_name='배달시간')),
                ('store_url', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='core.Category', verbose_name='카테고리명')),
            ],
        ),
    ]
