# Generated by Django 2.2.9 on 2020-02-11 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='univ_id',
            new_name='univ_name',
        ),
    ]
