# Generated by Django 2.2.9 on 2020-02-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='posting',
            name='create_date_string',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='max_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='menu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='timer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
