# Generated by Django 2.2.9 on 2020-02-11 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('max_num', models.IntegerField()),
                ('timer', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='univ_name',
            new_name='univ_id',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='category',
            new_name='category_id',
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=20)),
                ('posting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='core.Posting')),
            ],
        ),
        migrations.AddField(
            model_name='posting',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting', to='core.Store'),
        ),
    ]
