# Generated by Django 2.2.9 on 2020-02-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='chat_created',
            field=models.BooleanField(default=False),
        ),
    ]
