# Generated by Django 2.2.9 on 2020-02-19 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_posting_chat_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='now_num',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
