# Generated by Django 2.2.9 on 2020-02-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200218_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='create_date_string',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
