# Generated by Django 2.2.9 on 2020-02-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_posting_create_date_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='create_date_string',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
