# Generated by Django 2.2.9 on 2020-02-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Room',
            new_name='room',
        ),
    ]
