# Generated by Django 2.2.9 on 2020-02-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room_id',
            field=models.PositiveIntegerField(),
        ),
    ]
