# Generated by Django 2.2.9 on 2020-02-16 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='allowed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_user', to='account.Profile'),
        ),
    ]
