# Generated by Django 2.2.9 on 2020-02-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200216_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
