# Generated by Django 2.2.9 on 2020-02-19 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200219_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='now_number',
        ),
    ]
